# Generated by Django 3.1.1 on 2020-09-25 12:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=9, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_ranking', models.FloatField()),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.Users.upload_resume)),
            ],
        ),
    ]
