# Generated by Django 3.1.1 on 2020-09-25 12:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_resume',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.Users.upload_resume),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.Users.upload_photo),
        ),
    ]
