# Generated by Django 3.1.1 on 2020-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200925_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_email',
            field=models.CharField(default='admin@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
