# Generated by Django 3.1.1 on 2020-09-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200926_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_password',
        ),
    ]
