# Generated by Django 3.1.1 on 2020-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_users_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
